QMAKE_INCDIR_GLSLANG_GLSLANG = 
QMAKE_DEFINES_GLSLANG_GLSLANG = 
QMAKE_LIBS_GLSLANG_GLSLANG_RELEASE = $$[QT_INSTALL_LIBS/get]/libQt6BundledGlslang_Glslang.a
QMAKE_LIBS_GLSLANG_GLSLANG_DEBUG = $$[QT_INSTALL_LIBS/get]/libQt6BundledGlslang_Glslangd.a
