QMAKE_INCDIR_SPIRV_CROSS = 
QMAKE_DEFINES_SPIRV_CROSS = 
QMAKE_LIBS_SPIRV_CROSS_RELEASE = $$[QT_INSTALL_LIBS/get]/libQt6BundledSpirv_Cross.a
QMAKE_LIBS_SPIRV_CROSS_DEBUG = $$[QT_INSTALL_LIBS/get]/libQt6BundledSpirv_Crossd.a
