QMAKE_INCDIR_GLSLANG_OSDEPENDENT = 
QMAKE_DEFINES_GLSLANG_OSDEPENDENT = 
QMAKE_LIBS_GLSLANG_OSDEPENDENT_RELEASE = $$[QT_INSTALL_LIBS/get]/libQt6BundledGlslang_Osdependent.a
QMAKE_LIBS_GLSLANG_OSDEPENDENT_DEBUG = $$[QT_INSTALL_LIBS/get]/libQt6BundledGlslang_Osdependentd.a
