QMAKE_INCDIR_GLSLANG_SPIRV = 
QMAKE_DEFINES_GLSLANG_SPIRV = 
QMAKE_LIBS_GLSLANG_SPIRV_RELEASE = $$[QT_INSTALL_LIBS/get]/libQt6BundledGlslang_Spirv.a
QMAKE_LIBS_GLSLANG_SPIRV_DEBUG = $$[QT_INSTALL_LIBS/get]/libQt6BundledGlslang_Spirvd.a
