QMAKE_INCDIR_PCRE2 = C:/Qt/qtbase/src/3rdparty/pcre2/src
QMAKE_DEFINES_PCRE2 = PCRE2_CODE_UNIT_WIDTH=16 PCRE2_STATIC
QMAKE_LIBS_PCRE2_RELEASE = $$[QT_INSTALL_LIBS/get]/libQt6BundledPcre2.a
QMAKE_LIBS_PCRE2_DEBUG = $$[QT_INSTALL_LIBS/get]/libQt6BundledPcre2d.a
